# Generated by Django 4.2.3 on 2023-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_archivopdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo_pdf', models.FileField(upload_to='pdfs/')),
                ('materia', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArchivoPDF',
        ),
    ]
